# Generated by Django 5.2.4 on 2025-07-12 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('especialidades', '0001_initial'),
        ('pacientes', '0001_initial'),
        ('servicios', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('frecuencia', models.CharField(blank=True, max_length=100, null=True)),
                ('valido_hasta', models.DateField(blank=True, null=True, verbose_name='Válido hasta')),
                ('duracion', models.DurationField(help_text='Duración de la cita (hh:mm:ss)')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='especialidades.especialidad')),
                ('medico', models.ForeignKey(limit_choices_to={'rol': 'Medico'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
                ('servicio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios.servicio')),
            ],
        ),
    ]
