# Generated by Django 5.2.4 on 2025-07-17 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
        ('medicos', '0003_alter_medico_especialidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='frecuencia',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='valido_hasta',
        ),
        migrations.AlterField(
            model_name='cita',
            name='duracion',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='medico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='medicos.medico'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cita',
            name='motivo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
