# Generated by Django 5.2.4 on 2025-07-12 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=225)),
                ('apellidos', models.CharField(max_length=225)),
                ('fecha_nac', models.DateField(verbose_name='Fecha nacimiento')),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(max_length=10)),
                ('tipo_sangre', models.CharField(blank=True, max_length=3, null=True, verbose_name='Tipo sangre')),
                ('tipo_doc', models.CharField(max_length=50, verbose_name='Tipo documento')),
                ('num_doc', models.CharField(max_length=50, verbose_name='Número documento')),
                ('num_tel', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número teléfono')),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('estado_civil', models.CharField(blank=True, max_length=20, null=True, verbose_name='Estado civil')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
    ]
