# Generated by Django 5.2.4 on 2025-07-14 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_remove_paciente_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='correo',
            new_name='email',
        ),
    ]
