# Generated by Django 5.2.4 on 2025-07-15 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_rename_correo_paciente_email'),
        ('usuarios', '0003_remove_usuario_cedula_usuario_num_doc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='nombres',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='num_tel',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='tipo_doc',
        ),
        migrations.AddField(
            model_name='paciente',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario'),
        ),
    ]
