# Generated by Django 5.2.4 on 2025-07-15 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_remove_paciente_apellidos_remove_paciente_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_nac',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha nacimiento'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='num_doc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número documento'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
