# Generated by Django 5.2.4 on 2025-07-15 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0005_alter_paciente_edad_alter_paciente_fecha_nac_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='num_doc',
        ),
    ]
