# Generated by Django 5.2.4 on 2025-07-17 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0006_remove_paciente_num_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='fecha_nac',
            field=models.CharField(blank=True, null=True, verbose_name='Fecha nacimiento'),
        ),
    ]
