# Generated by Django 5.2.4 on 2025-07-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0007_alter_paciente_fecha_nac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='fecha_nac',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha nacimiento'),
        ),
    ]
