# Generated by Django 5.2.4 on 2025-07-16 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0001_initial'),
        ('usuarios', '0003_remove_usuario_cedula_usuario_num_doc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='num_doc',
        ),
        migrations.AlterField(
            model_name='medico',
            name='usuario',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario'),
            preserve_default=False,
        ),
    ]
