# Generated by Django 5.2.4 on 2025-07-16 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0001_initial'),
        ('medicos', '0002_remove_medico_num_doc_alter_medico_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='especialidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='especialidades.especialidad'),
            preserve_default=False,
        ),
    ]
