# Generated by Django 5.2.4 on 2025-07-16 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0001_initial'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='estado',
        ),
        migrations.AddField(
            model_name='servicio',
            name='especialidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='especialidades.especialidad'),
            preserve_default=False,
        ),
    ]
