# Generated by Django 5.2.4 on 2025-07-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_remove_servicio_estado_servicio_especialidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='duracion_estimada',
        ),
        migrations.AddField(
            model_name='servicio',
            name='duracion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
