# Generated by Django 5.2.4 on 2025-07-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_remove_servicio_duracion_estimada_servicio_duracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='duracion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
