# Generated by Django 5.2.4 on 2025-07-15 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_cedula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='cedula',
        ),
        migrations.AddField(
            model_name='usuario',
            name='num_doc',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='N°Doc'),
        ),
    ]
